In [2]:
import random
from deap import base, creator, tools, algorithms
import numpy as np
import math
import pandas as pd

In [21]:

EXCEL_NAME = "names.xlsx"
SHEET_NAME = "名簿"

# 列名
COL_NAME = "氏名"
COL_TARGET = "対象"
COL_BU = "部・室"
COL_KA = "課"
# 追加列名
COL_CLASS = "class"
COL_OUTPUT = "グループ分け"  # グループ分け名

# グループ分け設定
GROUP_PEOPLE_MIN = 4  # 1グループあたりの最少人数（割り切れない場合はグループによって+1人）

# 探索諸設定
N = 1000

# 重みづけ
WEIGHT1_CLASS = 1000
WEIGHT2_CLASS = 4
WEIGHT1_OUTPUT = 2
WEIGHT2_OUTPUT = 1

# 初期データ処理
df_origin = pd.read_excel(EXCEL_NAME, sheet_name=SHEET_NAME)
df = df_origin.copy()
df = df[df[COL_TARGET] == 1]
print(len(df), len(set(list(df[COL_NAME]))))
if len(df) != len(set(list(df[COL_NAME]))):
    print("名前が重複している人がいます。")
    sys.exit()
df[COL_CLASS] = df[COL_BU] + df[COL_KA]
classes = list(set(df[COL_CLASS]))
numbered_dict = {value: index for index, value in enumerate(classes)}
df[COL_CLASS] = df[COL_CLASS].replace(numbered_dict)

43 43

In [22]:
df

    対象 部・室  課  氏名  グループ分け1  グループ分け2  グループ分け3  class
0    1   a  a   A      5.0      1.0      1.0      3
2    1   a  a   C      6.0      6.0      3.0      3
3    1   a  a   D      1.0      2.0      8.0      3
5    1   b  a   F      4.0      0.0      5.0      7
6    1   b  a   G      5.0      8.0      7.0      7
7    1   b  a   H      1.0      3.0      0.0      7
8    1   c  a   I      0.0      9.0      7.0      4
9    1   c  a   J      3.0      4.0      6.0      4
10   1   c  a   K      2.0      6.0      1.0      4
11   1   c  a   L      8.0      2.0      2.0      4
12   1   c  a   M      6.0      8.0      9.0      4
13   1   c  a   N      7.0      5.0      5.0      4
14   1   c  a   O      5.0      1.0      0.0      4
15   1   c  a   P      3.0      5.0      4.0      4
16   1   d  a   Q      7.0      7.0      8.0      1
17   1   d  a   R      8.0      9.0      6.0      1
18   1   d  a   S      2.0      8.0      2.0      1
19   1   d  a   T      4.0      6.0      7.0      1
20   1   d  a   U      6.0      2.0      1.0      1
21   1   d  a   V      9.0      3.0      3.0      1
22   1   e  a   W      5.0      4.0      4.0      5
23   1   e  a   X      0.0      6.0      9.0      5
24   1   e  a   Y      8.0      7.0      8.0      5
25   1   e  a   Z      9.0      8.0      0.0      5
26   1   f  a  AA      7.0      4.0      5.0      0
27   1   f  a  AB      3.0      6.0      7.0      0
28   1   f  a  AC      2.0      0.0      3.0      0
29   1   g  a  AD      2.0      2.0      2.0      6
30   1   g  a  AE      1.0      0.0      1.0      6
31   1   g  a  AF      0.0      7.0      4.0      6
32   1   g  a  AG      9.0      1.0      7.0      6
33   1   g  a  AH      8.0      9.0      4.0      6
34   1   g  a  AI      3.0      3.0      9.0      6
35   1   h  a  AJ      4.0      7.0      8.0      8
36   1   h  a  AK      1.0      5.0      9.0      8
37   1   h  a  AL      8.0      1.0      0.0      8
38   1   h  a  AM      5.0      3.0      5.0      8
39   1   h  a  AN      2.0      4.0      6.0      8
40   1   h  a  AO      7.0      0.0      4.0      8
41   1   h  a  AP      6.0      8.0      2.0      8
42   1   i  a  AQ      9.0      9.0      1.0      2
43   1   i  a  AR      0.0      5.0      3.0      2
44   1   i  a  AS      4.0      2.0      6.0      2

In [23]:
l = list(df["グループ分け3"])
print(l)
random.shuffle(l)
print(l)

[1.0, 3.0, 8.0, 5.0, 7.0, 0.0, 7.0, 6.0, 1.0, 2.0, 9.0, 5.0, 0.0, 4.0, 8.0, 6.0, 2.0, 7.0, 1.0, 3.0, 4.0, 9.0, 8.0, 0.0, 5.0, 7.0, 3.0, 2.0, 1.0, 4.0, 7.0, 4.0, 9.0, 8.0, 9.0, 0.0, 5.0, 6.0, 4.0, 2.0, 1.0, 3.0, 6.0]
[8.0, 9.0, 7.0, 1.0, 0.0, 0.0, 7.0, 9.0, 6.0, 3.0, 9.0, 0.0, 4.0, 1.0, 1.0, 6.0, 6.0, 3.0, 7.0, 1.0, 4.0, 8.0, 5.0, 1.0, 7.0, 5.0, 7.0, 9.0, 8.0, 8.0, 4.0, 3.0, 4.0, 2.0, 3.0, 4.0, 5.0, 2.0, 5.0, 6.0, 2.0, 0.0, 2.0]

In [52]:
from collections import Counter

# リストの中から最も頻出な単語の要素数を返す。同じ課（class）の人と重複している人数を返す。
def _most_frequent_element_count(lst):
    if not lst:
        return 0  # リストが空の場合、0を返す
    element_counts = Counter(lst)  # リスト内の要素の出現回数をカウント
    most_common = element_counts.most_common(1)  # 最も多い要素とそのカウントを取得
    return most_common[0][1] - 1

def get_score_list_from_same_class_and_groups(df, group_member_list, target_col):  
    # 必要な列を辞書に変換してアクセスを高速化  
    target_dict = df.set_index(COL_NAME)[target_col].to_dict()  
    each_group_score_list = []  
    for member_list in group_member_list:  
        element_list = []  
        for name in member_list:  
            value = target_dict.get(name, None)  
            if value is not None:  
                try:  
                    element_list.append(int(value))  
                except ValueError:  
                    element_list.append(value)  
        each_group_score_list.append(_most_frequent_element_count(element_list))  
    return each_group_score_list  

# 単体のスコアのを取得
def score_details(df, group_dict):
    target_col_list = [COL_CLASS]
    # col名と重みのlistを作成
    for i in range(past_out_n):
        target_col_list.append(COL_OUTPUT + str(i+1))

    score_lists = []
    for target_col in target_col_list:
        group_member_list = group_dict
        each_group_score_list = get_score_list_from_same_class_and_groups(df, group_member_list.copy(), target_col)
        score_lists.append(each_group_score_list)
    return score_lists

def exchange_score(score_lists, weight1, weight2, weight3, weight4):
    score = 0
    score += weight3 * max(score_lists[0])
    score += weight4 * sum(score_lists[0])
    for score_list in score_lists[1:]:
        score += weight3 * max(score_list)
        score += weight4 * sum(score_list)
    return score

from collections import defaultdict

def group_names_by_list(group_list, name_list):
    grouped_names = defaultdict(list)
    for group, person in zip(group_list, name_list):
        grouped_names[group].append(person)
    result = [grouped_names[i] for i in range(len(grouped_names))]
    return result

past_out_n = 3
name = list(df["氏名"])
print(name)
print(l)
score_lists = score_details(df, group_names_by_list(l, name))
weight1 = 1000
weight2 = 4
weight3 = 2
weight4 = 1
score = exchange_score(score_lists, weight1, weight2, weight3, weight4)
score

['A', 'C', 'D', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'AA', 'AB', 'AC', 'AD', 'AE', 'AF', 'AG', 'AH', 'AI', 'AJ', 'AK', 'AL', 'AM', 'AN', 'AO', 'AP', 'AQ', 'AR', 'AS']
[8.0, 9.0, 7.0, 1.0, 0.0, 0.0, 7.0, 9.0, 6.0, 3.0, 9.0, 0.0, 4.0, 1.0, 1.0, 6.0, 6.0, 3.0, 7.0, 1.0, 4.0, 8.0, 5.0, 1.0, 7.0, 5.0, 7.0, 9.0, 8.0, 8.0, 4.0, 3.0, 4.0, 2.0, 3.0, 4.0, 5.0, 2.0, 5.0, 6.0, 2.0, 0.0, 2.0]

35

In [55]:
from collections import Counter, defaultdict

# 定数の定義
PAST_OUT_N = 3
WEIGHT1 = 1000
WEIGHT2 = 4
WEIGHT3 = 2
WEIGHT4 = 1

# リストの中から最も頻出な要素の数を返す。同じクラスの人数をカウントする関数
def most_frequent_element_count(lst):
    if not lst:
        return 0  # リストが空の場合、0を返す
    element_counts = Counter(lst)  # リスト内の要素の出現回数をカウント
    most_common = element_counts.most_common(1)  # 最も多い要素とそのカウントを取得
    return most_common[0][1] - 1

# グループリストと名前リストからグループ分けを行い、スコアを計算する関数
def calculate_total_score(df, group_list):
    name_list = list(df["氏名"])
    grouped_names = defaultdict(list)
    for group, person in zip(group_list, name_list):
        grouped_names[group].append(person)
    
    target_cols = [COL_CLASS] + [COL_OUTPUT + str(i+1) for i in range(PAST_OUT_N)]
    total_score = 0
    
    for target_col in target_cols:
        target_dict = df.set_index("氏名")[target_col].to_dict()
        group_scores = []
        for group in grouped_names.values():
            element_list = [target_dict.get(name) for name in group if target_dict.get(name) is not None]
            group_scores.append(most_frequent_element_count(element_list))
        total_score += WEIGHT3 * max(group_scores)
        total_score += WEIGHT4 * sum(group_scores)
    
    return total_score

# 実行例
# dfとグループリストlを用意して、スコアを算出
total_score = calculate_total_score(df, l)
print(total_score)

35

In [57]:
from collections import Counter, defaultdict

# 定数の定義
PAST_OUT_N = 3
WEIGHT1 = 1000
WEIGHT2 = 4
WEIGHT3 = 2
WEIGHT4 = 1

# リストの中から最も頻出な要素の数を返す。同じクラスの人数をカウントする関数
def most_frequent_element_count(lst):
    if not lst:
        return 0  # リストが空の場合、0を返す
    element_counts = Counter(lst)  # リスト内の要素の出現回数をカウント
    most_common = element_counts.most_common(1)  # 最も多い要素とそのカウントを取得
    return most_common[0][1] - 1

# グループリストと名前リストからグループ分けを行い、スコアを計算する関数
def calculate_score_details(df, group_list):
    name_list = list(df["氏名"])
    grouped_names = defaultdict(list)
    for group, person in zip(group_list, name_list):
        grouped_names[group].append(person)
    
    target_cols = [COL_CLASS] + [COL_OUTPUT + str(i+1) for i in range(PAST_OUT_N)]
    score_lists = []
    
    for target_col in target_cols:
        target_dict = df.set_index("氏名")[target_col].to_dict()
        group_scores = []
        for group in grouped_names.values():
            element_list = [target_dict.get(name) for name in group if target_dict.get(name) is not None]
            group_scores.append(most_frequent_element_count(element_list))
        score_lists.append(group_scores)
    
    return score_lists

# スコアリストを基に合計スコアを算出する関数
def calculate_total_score(score_lists):
    total_score = 0
    total_score += WEIGHT3 * max(score_lists[0])
    total_score += WEIGHT4 * sum(score_lists[0])
    
    for score_list in score_lists[1:]:
        total_score += WEIGHT3 * max(score_list)
        total_score += WEIGHT4 * sum(score_list)
    
    return total_score

# 実行例
def main(df, group_list):
    # スコアリストを計算
    score_lists = calculate_score_details(df, group_list)
    # 合計スコアを計算
    total_score = calculate_total_score(score_lists)
    return score_lists, total_score

# dfとグループリストlを用意して、スコアを算出
score_lists, total_score = main(df, l)
print(score_lists)
print(total_score)

[[1, 1, 1, 1, 1, 1, 0, 1, 1, 1], [1, 1, 0, 1, 0, 1, 1, 1, 0, 1], [0, 0, 1, 0, 1, 1, 0, 2, 0, 0], [1, 0, 0, 0, 0, 1, 0, 1, 0, 1]]
35